### ISSUE TITLE
Semicolon after namespace

### ISSUE THREAD

**Issue by embeddedden** [lxde/lximage-qt#112]
https://github.com/lxde/lximage-qt/blob/25d60d97280e7f905cfde31cfafbe2408789aeb8/src/mainwindow.h#L161

Is it ok? Why some namespaces are enclosed by semicolons?

**Comment by tsujan** [comment]
Redundant but harmless.

**Comment by embeddedden** [comment]
Better to delete them in order not to receive warnings?

**Comment by tsujan** [comment]
Yes!

**Comment by tsujan** [comment]
If you want to make a PR, please also fix other compiler warnings if they exist and their causes are clear.

**Comment by embeddedden** [comment]
Ok, as soon as I will be able to compile it :) 
I don't really understand where I should write my requests for help.
Is lxde mailing-list is suitable for this?

**Comment by agaida** [comment]
right now IRC is the preferred way - we are working on Discurse but right now this is a never ending story. Sad but true - but we have plans to force this after the upcoming release. Until then ...

As i said, the lxde list is mostly for LXDE, our forum with lists is not yet in a productive state.

**Comment by nathan-osman** [comment]
I believe this is resolved with #116.
