### ISSUE TITLE
cmake error "package 'libfm-qt' not found" resolved (?), linking cxx executable fails: "ld returned 1 exit status"

### ISSUE THREAD

**Issue by hashashini** [lxde/lximage-qt#4]
setup: 
menu-cache: ./configure --prefix=/usr
libfm: ./configure --without-gtk --sysconfdir=/etc --prefix=/usr
pcmanfm-qt: installed in /usr/local

---

<pre>build # cmake ..
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake (found version "4.8.5") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.38.2
-- checking for module 'libexif'
--   found libexif, version 0.6.21
-- checking for modules 'libfm-qt;libfm>=1.2'
--   package 'libfm-qt' not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:284 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:338 (_pkg_check_modules_internal)
  CMakeLists.txt:22 (pkg_check_modules)

-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- checking for module 'xfixes'
--   found xfixes, version 5.0.1
-- Configuring incomplete, errors occurred!
See also "/var/lib/gitcustoms/lximage-qt/build/CMakeFiles/CMakeOutput.log".
See also "/var/lib/gitcustoms/lximage-qt/build/CMakeFiles/CMakeError.log".
</pre>

---

<pre>build # less /var/lib/gitcustoms/lximage-qt/build/CMakeFiles/CMakeError.log | grep -i error
/var/lib/gitcustoms/lximage-qt/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: error: ‘Q_WS_WIN’ was not declared in this scope
gmake[1]: *** [CMakeFiles/cmTryCompileExec2861008438.dir/CheckSymbolExists.cxx.o] Error 1
gmake: *** [cmTryCompileExec2861008438/fast] Error 2
/var/lib/gitcustoms/lximage-qt/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: error: ‘Q_WS_QWS’ was not declared in this scope
gmake[1]: *** [CMakeFiles/cmTryCompileExec838586097.dir/CheckSymbolExists.cxx.o] Error 1
gmake: *** [cmTryCompileExec838586097/fast] Error 2
/var/lib/gitcustoms/lximage-qt/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: error: ‘Q_WS_MAC’ was not declared in this scope
gmake[1]: *** [CMakeFiles/cmTryCompileExec3483612841.dir/CheckSymbolExists.cxx.o] Error 1
gmake: *** [cmTryCompileExec3483612841/fast] Error 2
</pre>

<pre>build # less /var/lib/gitcustoms/lximage-qt/build/CMakeFiles/CMakeError.log | grep -i fail
Determining if the Q_WS_WIN exist failed with the following output:
CMakeFiles/cmTryCompileExec2861008438.dir/build.make:60: recipe for target 'CMakeFiles/cmTryCompileExec2861008438.dir/CheckSymbolExists.cxx.o' failed
Makefile:117: recipe for target 'cmTryCompileExec2861008438/fast' failed
Determining if the Q_WS_QWS exist failed with the following output:
CMakeFiles/cmTryCompileExec838586097.dir/build.make:60: recipe for target 'CMakeFiles/cmTryCompileExec838586097.dir/CheckSymbolExists.cxx.o' failed
Makefile:117: recipe for target 'cmTryCompileExec838586097/fast' failed
Determining if the Q_WS_MAC exist failed with the following output:
CMakeFiles/cmTryCompileExec3483612841.dir/build.make:60: recipe for target 'CMakeFiles/cmTryCompileExec3483612841.dir/CheckSymbolExists.cxx.o' failed
Makefile:117: recipe for target 'cmTryCompileExec3483612841/fast' failed
</pre>

---

partial "solution":
installed pcmanfm-qt in /usr with:

<pre>pcmanfm-qt/build # cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..</pre> 

(which seemed appropriate if like in my case libfm resides in /usr)
then (after "pcmanfm-qt/build # make && make install && ldconfig")

<pre>lximage-qt/build # cmake ..</pre> completes without error. <br />
(alternatively: pcmanfm-qt installed in /usr/local: "export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig" prior to executing "lximage-qt/build # cmake ..")<br />

but (in both cases):
<pre>lximage-qt/build # make
[  2%] Automoc for target lximage-qt
[  2%] Built target lximage-qt_automoc                                                                                                                                                                            
Linking CXX executable lximage-qt
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.2/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtGui                                                                                                                
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.2/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtDBus
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.2/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtXml
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.2/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtCore
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.2/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtGui
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.2/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtDBus
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.2/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtXml
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.2/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtCore
collect2: error: ld returned 1 exit status
src/CMakeFiles/lximage-qt.dir/build.make:511: recipe for target 'src/lximage-qt' failed
make[2]: *** [src/lximage-qt] Error 1
CMakeFiles/Makefile2:80: recipe for target 'src/CMakeFiles/lximage-qt.dir/all' failed
make[1]: *** [src/CMakeFiles/lximage-qt.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2</pre>

running "lximage-qt/build # cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .." instead of "lximage-qt/build # cmake .." makes no difference either.

"# libtool --finish /usr/lib64" also didn't help.

any advise?

---

edit2:
libQtCore.so, libQtGui.so, libQtXml.so, libQtDBus.so located in /usr/lib64/qt4/ and linked to the respective .so.4.8.5 

---

edit: removed: how i got there

**Comment by vrkansagara** [comment]
@jleclanche  it's work . thanks
