### ISSUE TITLE
Feature request: Option for the application window to resize automatically based on image dimensions

### ISSUE THREAD

**Issue by ms6676749** [lxde/lximage-qt#43]
Archlinux
lxqt 0.10.0
Xfwm4 4.12.3
lximage-qt 0.4.0

For example, open an image and lximage-qt will open it centerscreen in its native dimension or, if the image is too large, fit the image to the width or height of the screen accordingly.  Currently, lximage opens every image in a 553x432 window, which is pretty small on a 1920x1080 screen.

**Comment by tsujan** [comment]
closed by #45
