### ISSUE TITLE
Gif files

### ISSUE THREAD

**Issue by hawkeyed** [lxde/lximage-qt#5]
The program doesn't play gif files. When I open a gif file,it shows the first frame.

**Comment by Vladimir-csp** [comment]
I second that

**Comment by tsujan** [comment]
+1
I'm waiting for a decision about #45 to add support for GIF animation.

**Comment by tsujan** [comment]
GIF animation is added at https://github.com/lxde/lximage-qt/pull/46. Please test it!

**Comment by Pr0Wolf29** [comment]
Works on my machine.
