### ISSUE TITLE
Problem displaying PNG with transparency

### ISSUE THREAD

**Issue by pooka109** [lxde/lximage-qt#6]
lximage-qt, as of git revision 953d069 (running on Slackware 14.1, with qt 4.8.5), doesn't display at least one PNG with a transparent background properly.  More specifically, it does display it properly for a split second, but then covers it over with an entirely black square.  The PNG file in question is attached.

![endlessknot](https://cloud.githubusercontent.com/assets/7695641/3077486/2eb7b714-e42f-11e3-88cb-5aea6eb31e3a.png)

**Comment by torto9** [comment]
The same thing happens with indexed images: they are shown really dark when zoomed in or out.
Returning from ImageView::generateCache() workarounds the problem.
