### ISSUE TITLE
Capture an area of the screen.

### ISSUE THREAD

**Issue by selairi** [lxde/lximage-qt#85]
I have just upload to screenshot-region branch an screenshot option. It only captures an area of the screen. If nobody is against, I will merge to master branch.
![screenshotarea](https://cloud.githubusercontent.com/assets/1163139/22390053/252d2e0a-e4e9-11e6-849c-a49a5ec65f08.png)

**Comment by palinek** [comment]
Why didn't you create a PR for it?

**Comment by pmattern** [comment]
> Why didn't you create a PR for it?

Indeed. This is not the first time you're asked this question.

**Comment by selairi** [comment]
Sorry, I have added a PR:

https://github.com/lxde/lximage-qt/pull/86

2017-01-28 1:09 GMT+01:00 Peter Mattern <notifications@github.com>:

**Comment by agaida** [comment]
should be closed with the merge of https://github.com/lxde/lximage-qt/pull/86
