### ISSUE TITLE
LXImage charactercoding error

### ISSUE THREAD

**Issue by szg0000** [lxde/lximage-qt#89]
LXImage viewer open file panel character coding error. Picture attached.
![lximageviewer_charactercoding_fails](https://cloud.githubusercontent.com/assets/18247040/23832903/4cd39b84-073e-11e7-9e35-03c17ebef8ed.png)

LXImage about window screenshot:
![lximage_about](https://cloud.githubusercontent.com/assets/18247040/23832965/272c222e-073f-11e7-8729-252175237d5b.png)

"echo $LANG" command returns nothing.

**Comment by tsujan** [comment]
Could you please paste the name of those files here? Do they have special characters?

**Comment by szg0000** [comment]
Sure.
The firs where the arrow points "Képek". The second is "Letöltések"

**Comment by pmattern** [comment]
> "echo $LANG" command returns nothing.

Could you post the output of `locale` then?

Also, it would be interesting to know what the folder in question looks like in file managers, in particular in PCManFM-Qt.

**Comment by tsujan** [comment]
I can't reproduce the issue here, whether under LXQt or under KDE.

I think you use Gnome; am I right? The problem may be because of the poor Qt support there.

BTW, the similar problem I'd encountered before was about FreeBSD. I guess you use Linux.

**Comment by szg0000** [comment]
I am under LXQt, Debian stretch(sid).
Here is my locale output:

szg@debian:~$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
szg@debian:~$

There is no problem with PCManFM-Qt, the folder names are perfent. Only LXImage affected.

**Comment by tsujan** [comment]
> I am under LXQt

Sorry, my mistake; I thought those titlebars were from Gnome.

> Here is my locale output: ...

For some reason, UTF-8 isn't enabled in your case:

Here:

````
$ locale -a
C
en_US.utf8
POSIX
````
And:

````
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
````

I don't know how pcmanfm-qt shows those folder names correctly -- maybe there's something in libfm.

**Comment by tsujan** [comment]
I don't think this is an lximage-qt problem. It should be about how Qt file dialog shows file names with special characters in them. It can't without utf-8 locale.

**Comment by szg0000** [comment]
Arora web browser has the same problem, so this can be a Qt issue, not lximage-qt.

**Comment by szg0000** [comment]
I found the solution. The problem was with the "LXQt Locale Configuration". Maybe other program overwrited the country setting. I am closing this issue and open an another with relevant title.
Thanks.
