### ISSUE TITLE
Change directory where screenshots are saved

### ISSUE THREAD

**Issue by Serkan-devel** [lxde/lximage-qt#91]
It seems to be inpractical to save screenshots in the home directory rather than a dedicated Photos directory.

Is there an option to set the save directory manually?

**Comment by tsujan** [comment]
You could save a screenshot anywhere by using the "Save As" menu-item.

**Comment by Serkan-devel** [comment]
But when hitting the 'print' I can't find  selection for that.
But is Lximage-qt used for taking screenshots when hitting the 'print'-button?

![grafik](https://cloud.githubusercontent.com/assets/16866642/25575408/66f71794-2e57-11e7-87c5-8238f1174f82.png)

This is the issue I currently have

**Comment by tsujan** [comment]
With the latest LXQt, Print calls `lximage-qt -s` by default, which opens this dialog:

![dialog](https://cloud.githubusercontent.com/assets/981076/25575624/43c5d15e-2e6e-11e7-9516-6f8edcdd562a.png)

After you click OK, an instance of lximage-qt will show the screenshot and you could save it anywhere.

Have you given Print to Scrot or another screenshot utility? See Configuration Center → Shortcut keys. Scrot is a nice screenshot utility and you could use it in different ways but it doesn't belong to LXQt

**Comment by tsujan** [comment]
BTW, Scrot might have been the default in older versions of LXQt -- if I remember correctly. Your attached screenshot shows that those images are created by scrot, not by lximage-qt. Closing this.
