### ISSUE TITLE
Add some kind of upload functionality

### ISSUE THREAD

**Issue by agaida** [lxde/lximage-qt#98]
it would be nice if it would possible without hard-coding possible upload targets

**Comment by tsujan** [comment]
Sorry if this is a stupid question -- I always upload things with browser

Could you please be more specific about how it should be? A general sketch?

**Comment by agaida** [comment]
like in the former screengrab - a functionality to upload screenshots to imgur and other services

**Comment by tsujan** [comment]
I need to look into the code of a Qt app that does the same thing or maybe someone who has done it before could add a PR.

**Comment by agaida** [comment]
Maybe it can be done with some kind of bindings that don't require a recompile after adding an upload target - that would be really cool.

**Comment by agaida** [comment]
erm - not that important, but very comfty :P

**Comment by nathan-osman** [comment]
I submitted a pull request that achieves this and includes support for Imgur.

**Comment by tsujan** [comment]
@nathan-osman Thanks for your contribution!
